### PR TITLE
IOS17 fix

### PR DESCRIPTION
**Pull request by remipou**

### CODE REVIEW

**Comment by R3DST0RM** [comment]
While this works, I think this will be superseded once this PR is done: https://github.com/vonovak/react-native-add-calendar-event/pull/181

**Comment by GeorgiIvanovPXL** [comment]
Can it be merged with main? How can I use it in the meantime?

**Comment by rvasseur31** [comment]
> Can it be merged with main? How can I use it in the meantime?

Use it with patch-package

**Comment by vonovak** [comment]
I'd like to merge #181 but there is an unresolved comment here https://github.com/vonovak/react-native-add-calendar-event/pull/181#issuecomment-1826884886

if someone wants to get that done, please check out the PR branch and finish what I'm asking for in the comment. Thank you! :)

I'll close this PR now, because I want to accept #181 instead, when it's done

**Pull request closed without merging**
